export const AUTOCOMPLETE_SELECTION = "AUTOCOMPLETE_SELECTION";
export const AUTOCOMPLETE_DOWN = "AUTOCOMPLETE_DOWN";
export const AUTOCOMPLETE_UP = "AUTOCOMPLETE_UP";

export const AUTOCOMPLETE_COMMANDS = {
  Tab: AUTOCOMPLETE_SELECTION,
  Down: AUTOCOMPLETE_DOWN,
  ArrowDown: AUTOCOMPLETE_DOWN,
  Up: AUTOCOMPLETE_UP,
  ArrowUp: AUTOCOMPLETE_UP,
  Enter: AUTOCOMPLETE_SELECTION,
};

export function getAutocompleteCommand(key) {
  return AUTOCOMPLETE_COMMANDS[key];
}
