const PEOPLE = `Rony Abovitz
Josh Abramson
Brian Acton
Rick Adams
Jay Adelson
Trip Adler
Dinesh Agarwal
Ritesh Agarwal
Bhavish Aggarwal
Christopher Ahlberg
Luis von Ahn
Sujayath Ali
Jeremy Allaire
Joseph J. Allaire
Paul Allen
Dmitri Alperovitch
Sam Altman
Brian Alvey
Tom Anderson
Marc Andreessen
Andrey Andreev
Ronnie Apteker
Marco Arment
Heather Armstrong
Jeff Arnold
Mohit Aron
Samir Arora
Trishneet Arora
Michael Arrington
Peter Arvai
Alexander Asseily
Jeff Atwood
Ali Aydar
Nevzat Aydin
Calvin Ayre
Kunal Bahl
Ajit Balakrishnan
Scott Banister
Binny Bansal
Jyoti Bansal
Rohit Bansal
Sachin Bansal
Peter Barrett
Matt Barrie
Rich Barton
David Baszucki
Jeff Bates
Micahel Baum
Patrick Baynes
Andy Bechtolsheim
Benjamin Bejbaum
Gordon Bell
Scott Belsky
Marc Benioff
Dan Benjamin
Tikhon Bernstam
Jeff Bezos
Sabeer Bhatia
Aneel Bhusri
Gina Bianchini
Noel Biderman
Sanjeev Bikhchandani
Willem Van Biljon
Eric Bina
Christophe Bisciglia
Gagan Biyani
Trevor Blackwell
Steve Blank
Nathan Blecharczyk
Ryan Block
David Bohnett
Cliff Boro
Eric Boyko
Alan Braverman
Sergey Brin
Juliette Brindak
Wendell Brown
Paul Buchheit
Matthew Buckland
Paul Budnitz
Ronald T. Burr
Leah Busque
Stewart Butterfield
David Byttow
Jason Calacanis
Dalton Caldwell
Jon Callas
Garrett Camp
Colin Campbell
Daniel Cane
Mike Cannon-Brookes
Carlos Cardona
John Carmack
Michael Carter
Martin Casado
Steve Case
Pete Cashmore
Maciej Ceglowski
Rohit Chadda
Gurbaksh Chahal
Wayne Chang
Stephen Chao
Shaherose Charania
Charlie Cheever
Paul Chen
Steve Chen
Brian Chesky
Alex Chesterman
Ben Chestnut
Pranay Chulet
Lew Cirne
James H. Clark
Alon Nisim Cohen
Bram Cohen
Scott Cook
Stephen Cohen
John Collison
Patrick Collison
Parker Conrad
Michael Cowpland
Andrew Crawford
Dennis Crowley
Mark Cuban
Nick D'Aloisio
Adam D'Angelo
Ben Darnell
Sky Dayton
Nicolas De Santis
Bart Decrem
Michael Dell
Nick Denton
Bharat Desai
Graeme Devine
Chris DeWolfe
Satish Dharmaraj
Roger Dickey
Ryan Disraeli
Chris Dixon
Dan Dodge
Pieter van der Does
Ralph Dommermuth
John Donahoe
Jack Dorsey
Scott Dorsey
Larry Drebes
Rod Drury
Adam Dunkels
David Duffield
Kris Duggan
Phil Dumontet
Andy Dunn
Pavel Durov
Joshua Dziabiak
Daniel Ek
Sean Ellis
Larry Ellison
Jeri Ellsworth
John Elvesjo
Judith Estrin
Batara Eto
Marc Ewing
Tony Fadell
Mike Faith
Caterina Fake
Steffan Sondermark Fallesen
Shawn Fanning
Faisal Farooqui
Scott Farquhar
Rahim Fazal
Arash Ferdowsi
Bran Ferren
David Filo
Ryan Finley
Jon Fisher
Rob Fishman
Mark Fletcher
Pete Flint
Theodor Forselius
Justin Frankel
Jared Friedman
Nat Friedman
Janus Friis
Gian Fulgoni
Marcos Galperin
Bill Gates
Dirk Gates
Jonathan Gay
Joe Gebbia
Adam Gibson
Stephen Gilfus
Bruce Gilliat
Noah Glass
Craig Taro Gold
Bryan Goldberg
Jason Goldberg
Anthony Goldbloom
David Goldman
Adam Goldstein
Vishal Gondal
Otavio Good
Kris Gopalakrishnan
Terry Gou
Andrew Gower
Paul Graham
Jeff Green
Logan Green
Josh Greenberg
Meron Gribetz
Fabrice Grinda
Daniel Gross
Tom Gruber
Garrett Gruener
Dominique Guinard
Vikas Gupta
Andi Gutmans
Oleg Gutsol
Daniel Ha
Simon Hackett
Eric Hahn
Brian Halligan
Jeff Hammerbacher
John Hanke
David Heinemeier Hansson
Mike Harrington
Julia Hartz
Kevin Hartz
Will Harvey
Reed Hastings
Trip Hawkins
Jared Hecht
Scott Heiferman
Ahti Heinla
Brett Helm
Cal Henderson
Kevin Henrikson
Jack Herrick
Joe Hewitt
Danny Hillis
David Hindawi
Orion Hindawi
Alexa Hirschfeld
James Hirschfeld
Jeremy Hitchcock
Veda Hlubinka-Cook
Andy Hobsbawm
Reid Hoffman
Ryan Holmes
Bri Holt
Dietmar Hopp
Ben Horowitz
Meg Hourihan
Drew Houston
Ken Howery
Tony Hsieh
Jen-Hsun Huang
Ma Huateng
Arianna Huffington
Steve Huffman
Chris Hughes
Chad Hurley
Dave Hyatt
P.J. Hyett
Aaron Iba
Miguel de Icaza
Brendan Iribe
Subrah Iyar
Charlie Jackson
Naveen Jain
Sumit Jain
Josh James
Philip J. K. James
Xeni Jardin
Jack Jia
Steve Jobs
Bryan Johnson
Lawrence Jones
Michael Jones
Vikas Joshi
Lei Jun
Tomer Kagan
Brewster Kahle
Philippe Kahn
Travis Kalanick
Justin Kan
Philip J. Kaplan
Amit Kapur
Jawed Karim
Alex Karp
David Karp
Kenji Kasahara
Eugene Kaspersky
Natalya Kaspersky
Brad Keywell
Salman Khan
Vinod Khosla
Spencer Kimball
Zach Klein
OD Kobo
Ruslan Kogan
Mahshad Koohgoli
Josh Kopelman
Jan Koum
Shlomo Kramer
Gary Kremen
Mike Krieger
Scott Kurnit
George Kurtz
Sandra Kurtzig
Joshua Kushner
Willem Van Lancker
Renaud Laplanche
Curtis Lee
Doug Leeds
Eric Lefkofsky
William LeGate
Howard Lerman
Sandy Lerner
Max Levchin
Aaron Levie
Jeremy Levitt
Robin Li
Kenneth Lin
Vinny Lingham
Jesse Lipson
Ted Livingston
Andrea Lo
Claes Loberg
Jake Lodwick
Joe Lonsdale
Marc Lore
Martin Lorentzon
Palmer Luckey
Tobias Lütke
Eric Ly
Michael Richard Lynch
Barrett Lyon
Adam Lyons
Jack Ma
Melanie Perkins
Igor Magazinnik
Chris Malachowsky
Kumar Malavalli
Rob Malda
Vikas Malpani
John Manoogian III
Talmon Marco
Clate Mask
Andrew Mason
Natalie Massenet
Daniel Mattes
Peter Mattis
Jed McCaleb
Andrew McCollum
Mike McCue
Jim McKelvey
Nick McKeown
William von Meister
Jordan Mendelson
Dwight Merriman
Heidi Messer
Stephen Messer
Loïc Le Meur
Andrew Michael
Matt Mickiewicz
Bob Miner
Rich Miner
Halsey McLean Minor
Kavin Bharti Mittal
Louis Monier
Darius A. Monsef IV
Mike Moradian
Brit Morin
Dave Morin
Dustin Moskovitz
Matt Mullenweg
Bobby Murphy
N. R. Narayana Murthy
Elon Musk
Demet Mutlu
Shiv Nadar
Satya Nadella
Mariam Naficy
Nalden
Divya Narendra
Ted Nash
Ashwin Navin
Col Needham
Seth Neiman
Gabe Newell
Craig Newmark
Bill Nguyen
Chris Nicholson
Preetish Nijhawan
Nandan Nilekani
Hiroyuki Nishimura
Daniel Nissan
Phiwa Nkambule
Luke Nosek
Ed Oates
Kevin O'Connor
Alexis Ohanian
Shaul Olmert
Pierre Omidyar
Alec Oxenford
Raphael Ouzan
Stepan Pachikov
Larry Page
Vijay Pandurangan
James Park
Sean Parker
Bob Parsons
Ali Partovi
Ben Pasternak
Narendra Patni
Aaron Patzer
Sunil Paul
Bo Peabody
Barney Pell
Robert Pera
Jonah Peretti
Markus Persson
Jeffrey Peterson
Dan Pickett
Mark Pincus
Adam Pisoni
Hasso Plattner
Kim Polese
Christopher Poole
Joris Poort
Bhargav Sri Prakash
Vipul Ved Prakash
Azim Premji
Tom Preston-Werner
Curtis Priem
Tom Proulx
Jeff Pulver
Liu Qiangdong
Ashley Qualls
Hooman Radfar
N. S. Raghavan
Dhiraj Rajaram
Aneel Ranadive
Vivek Ranadive
Jerry Rao
Osman Rashid
Aza Raskin
Jens Eilstrup Rasmussen
Lars Rasmussen
Eric Ries
Jordan Ritter
Jesse Robbins
John Roberts
Michael Robertson
Peter Rojas
Martin Roscheisen
Kevin Rose
Philip Rosedale
Bob Rosenschein
Justin Rosenstein
Blake Ross
Andy Rubin
Christian Rudder
Matt Rutledge
Kevin P. Ryan
David O. Sacks
Alexander Samwer
Larry Sanger
Eduardo Saverin
Michael J. Saylor
Michael Sayman
Alan Schaaf
Joshua Schachter
Stephan Schambach
Roman Scharf
Eric Schiermeyer
Frank Schilling
Ernesto Schmitt
Arnout Schuijff
Paul Sciarra
Adrian Scott
John Sculley
Michael Seibel
Jeff Seibert
Naveen Selvadurai
Nahum Sharfman
Tina Sharkey
Liron Shapira
Vijay Shekhar Sharma
Evan Sharp
Emmett Shear
S. D. Shibulal
Will Shu
Mark Shuttleworth
Gil Shwed
Ben Silbermann
Russel Simmons
Charles Simonyi
Pradeep Sindhu
Jeet Singh
Param Singh
Gunjan Sinha
Rashmi Sinha
Jeffrey Skoll
Dylan Smith
Jack Smith
Jeffrey Christopher Smith
Javier Soltero
Ashok Soota
Angelo Sotira
Mark Spencer
Evan Spiegel
Joel Spolsky
Eric Stanley
Chad Steelberg
Ryan Steelberg
David A. Steinberg
Stephen Stokols
Biz Stone
Jeremy Stoppelman
Alexander Straub
Ludvig Strigeus
Krishna Subramanian
Zeev Suraski
John A. Swanson
Aaron Swartz
Patrick Sweeney
Kevin Systrom
David Tabizel
Richard (Dick) Talens
Garry Tan
Yoshikazu Tanaka
Tolga Tanriseven
Bret Taylor
Keith Teare
Rodrigo Teijeiro
Astro Teller
Chuck Templeton
Milun Tesovic
Naveen Tewari
Peter Thiel
Steven Thomas
Sebastian Thrun
Linus Torvalds
Gina Trapani
Vlad Trifa
Benjamin Trott
Mena Trott
Penelope Trunk
Janie Tsao
Victor Tsao
Klaus Tschira
Greg Tseng
Bhavin Turakhia
Divyank Turakhia
Isaiah Turner
Tien Tzuo
David Ulevitch
Deena Varshavskaya
Raj Vattikuti
Ricky Van Veen
Juan Villalonga
Kyle Vogt
Anubhav Wadhwa
Romesh Wadhwani
Dan Wagner
Todd Wagner
Justin Waldron
Jimmy Wales
John Walker
Michael Walrath
Chris Wanstrath
David Warthen
Matt Watson
Lynda Weinman
Andrew Weinreich
Claus Wellenreuther
Jay Westerdal
Evan Williams
Maisie Williams
Jake Winebaum
Whitney Wolfe
Brian Wong
Steven Woods
Steve Wozniak
Graham Wylie
Eric Xu
Rahul Yadav
Sam Yagan
David Yang
Jerry Yang
Richard Yoo
Kyle York
Bob Young
Peggy Yu
Jonathan Zarra
Niklas Zennström
Ilya Zhitomirskiy
Min Zhu
John Zimmer
Phil Zimmermann
Zohar Zisapel
Mark Zuckerberg`
  .split("\n")
  .map((name, id) => {
    let image = null;
    if (name === "Mark Zuckerberg") {
      image =
        "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Mark_Zuckerberg_F8_2018_Keynote_%28cropped_2%29.jpg/440px-Mark_Zuckerberg_F8_2018_Keynote_%28cropped_2%29.jpg";
    } else if (name === "Mark Cuban") {
      image =
        "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Mark_Cuban_by_Gage_Skidmore.jpg/440px-Mark_Cuban_by_Gage_Skidmore.jpg";
    }
    return { name, id, image };
  });

export default PEOPLE;
